default_page:
    path:      /
    defaults:  { _controller: AppBundle:Default:index}
login_page:
    path:      /login
    defaults:  { _controller: AppBundle:Main:login}
logout_page:
    path:      /logout
    defaults:  { _controller: AppBundle:Main:logout}
register_page:
    path:      /register
    defaults:  { _controller: AppBundle:Main:register}
main_json:
    path:      /json-valid/{actionType}
    defaults:  { _controller: AppBundle:Main:jsonValidation}
    requirements:
        actionType: '\w+'