default_page:
    path:      /
    defaults:  { _controller: AppBundle:Default:index}
login_page:
    path:      /login
    defaults:  { _controller: AppBundle:Main:login}
login_json:
    path:      /login/json
    defaults:  { _controller: AppBundle:Main:json}